### ISSUE TITLE
Statmodding: Zeros

### ISSUE THREAD

**Issue by wafflesx90** [Tonic-Box/D3ROS-Modding-Guide#2]
Hello,
First of all, I appreciate your work and everyone involved. Also, I have been following along with your modding guide using the tools you provide and suggest in your hub. Awesome work!

I was pretty easily able to navigate the advanced modding series, but found myself a little more lost in this series. I was not able to make the mechanics of the demon hunter work so, I tried the necromancer and using some of the math from the other series was able to get almost all zeros.

The problem I am facing is, the necromancer on his (dps/dmg?) icon I still have about 1198K showing on the tool tip with the sword, everything else is zeros. The shield, the ++, str, dex, int, vit all zeros. 

"Then just stack damage and damage % on your gear and weapon (with this you can actually use a weapon)." 
I applied the following to my gear, and padded the rest with Damage 10-40% and 5610-6975 Damage sprinkled in on the gear. 
        4x 495-787 Strength
        4x 495-787 Intelligence
        4x 495-787 Dexterity
        4x 495-787 Vitality
I guess my question is, did I pad too much dmg on my gear or did I miss a stat field to lower that dps field on the character sheet? When I change one or the other it seems to offset too much. Also, do you not use pickup radius and stuff? or is that why I have too much dmg, by not using the other affixes. I know this is a lot, but just looking for any clarification.

Thank you everyone involved!
A Diablo fan!

**Comment by Tonic-Box** [comment]
Fot the damage, thats demon hunter with the sharp shooter passive and -150 crit like i said in guide.

The buffs from that passive will bring you to 0

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Tonic-Box** [comment]
With out that buff stack tho, you'll need to find a different way to do damage. But as that buff stacks to its maximum #, it will force your dps back to 0.
